# Generated by Django 5.0 on 2024-03-01 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='postcomment',
            name='comment_content',
            field=models.TextField(blank=True, null=True),
        ),
    ]
