# Generated by Django 5.0 on 2024-02-05 15:44

import cloudinary.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CollegeProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('college_name', models.CharField(max_length=50)),
                ('college_slug', models.SlugField(max_length=100, unique=True)),
                ('college_logo', cloudinary.models.CloudinaryField(max_length=255, verbose_name='profileImage')),
                ('cover_image', cloudinary.models.CloudinaryField(max_length=255, verbose_name='coverImage')),
                ('website_url', models.URLField()),
                ('address', models.CharField(max_length=50)),
                ('phone_number', models.CharField(max_length=50)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
