# Generated by Django 5.0 on 2024-02-23 18:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_studenteducation'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentFriends',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Accepted', 'Accepted'), ('Decline', 'Decline')], max_length=10)),
                ('request_send', models.DateTimeField(auto_now_add=True)),
                ('accept_request', models.DateTimeField(blank=True, null=True)),
                ('friend', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='friend', to='student.studentprofile')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student', to='student.studentprofile')),
            ],
        ),
    ]
